[package]
name = "test_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.13.0", features = ["wav"] }
rand = { version = "0.8.5", features = ["small_rng"] }
bevy_ecs_tilemap = { git = "https://github.com/rparrett/bevy_ecs_tilemap", branch = "bevy13" }
bevy-inspector-egui = "0.23.4"

[profile.dev.package."*"]
opt-level = 3

[lints]
clippy.type_complexity = "allow"